command: [
  "flask",
  "--app",
  "app.py",
  "run"
]

env:
  - name: DATABRICKS_DASHBOARD_VA_ID
    valueFrom: 'DATABRICKS_DASHBOARD_VA_ID'
  - name: DATABRICKS_DASHBOARD_LTC_ID
    valueFrom: 'DATABRICKS_DASHBOARD_LTC_ID'
  - name: DATABRICKS_GENIE_SPACE_VA_ID
    valueFrom: 'DATABRICKS_GENIE_SPACE_VA_ID'
  - name: DATABRICKS_GENIE_SPACE_LTC_ID
    valueFrom: 'DATABRICKS_GENIE_SPACE_LTC_ID'

# This APP uses User OAuth token generated when the user logs to the APP. If the OAuth token is disable, this will rely of the PAT token that should be placed here.    
  - name: DATABRICKS_PAT_TOKEN 
    valueFrom: 'DATABRICKS_PAT_TOKEN'